import type { Metadata } from "next";
import "./globals.css";
import { RootLayoutView } from "./root_layout_view.tsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <RootLayoutView>{children}</RootLayoutView>;
}
